/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redeneural.view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Scanner;
import redeneural.model.Neuronio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import redeneural.Backpropagation;

/**
 *
 * @author aflemes
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    private Backpropagation rede;
    private Double[][] patternInput   = new Double[1][17];
    private Double[][] expectedOutput = new Double[1][10]; 
    private ArrayList<Neuronio> lstResultados = new ArrayList<Neuronio>();
    NumberFormat formater = new DecimalFormat("#0.000000");
    
    public Interface() {
        initComponents();
        initRede();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTestValores = new javax.swing.JTextField();
        jMessage = new javax.swing.JLabel();
        jMatrizConfusao = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar Treinamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Iniciar Amostra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Neurônio", "Saída"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        jButton3.setText("Testar valores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTestValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestValoresActionPerformed(evt);
            }
        });

        jMessage.setPreferredSize(new java.awt.Dimension(34, 14));

        jMatrizConfusao.setText("Matriz de Confusão");
        jMatrizConfusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatrizConfusaoActionPerformed(evt);
            }
        });

        jButton4.setText("Iniciar Teste");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTestValores)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMatrizConfusao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTestValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMatrizConfusao))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        initTreinamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadAmostraTemporaria();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTestValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestValoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestValoresActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Double[][] patternInputUniq   = new Double[1][16];
        Double[][] expectedOutputUniq = new Double[1][10];
        String[] split = jTestValores.getText().split(",");
        int neuronioEsperado = 0,indice = 0;
        Double valor = 0.0;
        
        if (split.length != 17){
            JOptionPane.showMessageDialog(null, "Quantidade de dados teste inválido!", "Informacao!", JOptionPane.ERROR_MESSAGE, null);
            return;
        }
        for (int i = 0; i < split.length - 1; i++) {
            valor = Double.parseDouble(split[i]);
            if (valor > 0)
                valor = valor / 10;

            patternInputUniq[indice][i] = valor;
        }
        neuronioEsperado = Integer.parseInt(split[split.length - 1]);
        
        for (int i = 0; i < 10; i++) {
            //a ultima posicao do arquivo e destinado a classe esperada
            if ((i + 1) == neuronioEsperado){
                expectedOutputUniq[indice][i] = 1.0;
            }
            else
                expectedOutputUniq[indice][i] = 0.0;
        }
        
        rede.setTrainingData(patternInputUniq, expectedOutputUniq);
               
        double erro = rede.train(100); //treinamento
        
        listaResultadosTela(neuronioEsperado);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listaResultadosTela(int neuronioEsperado){
        Neuronio neuronioTemp         = new Neuronio();
        Double maiorValor = 0.0;
        Double[] saida = rede.getOutput();
        int indice = 0;
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTabela.getModel();
        tabelaModelo.setNumRows(0); //limpa a tabela
        for (int i = 0; i < saida.length; i++) {//seta cor
            tabelaModelo.addRow(new String[]{"Neuronio " + (i + 1), "" + formater.format(saida[i])}); 
            
            if (saida[i] > maiorValor){
                indice = i;
                maiorValor = saida[i];
            }
        }
        neuronioTemp.setId(neuronioEsperado);
        neuronioTemp.setResultadoObtido(indice);
                
        lstResultados.add(neuronioTemp);
        
        jTabela.setRowSelectionInterval(indice, indice);
    }
    private void jMatrizConfusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatrizConfusaoActionPerformed
        // TODO add your handling code here:
        System.out.println(" lstResultados.size() " + lstResultados.size());
        MatrizConfusao jMatrizConfusao = new MatrizConfusao(lstResultados);
        jMatrizConfusao.setVisible(true);
    }//GEN-LAST:event_jMatrizConfusaoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    private void initTreinamento(){
        String[] split;
        String linha;
        double valor = 0.0;
        int neuronioEsperado = 0, qtdeLinhasLidas = 0;
        
        long tempoInicial = System.currentTimeMillis();
        
        try {
            FileReader arq = new FileReader("src\\redeneural\\data\\pendigits.trainning");
            BufferedReader lerArq = new BufferedReader(arq);
            linha = lerArq.readLine(); // lê a primeira linha           
            
            jMessage.setText("Treinando a rede neural, aguarde...");
            
            while (linha != null) {
                split = linha.split(",");
                
                for (int i = 0; i < split.length - 1; i++) {
                    valor = Double.parseDouble(split[i]);
                    if (valor > 0)
                        valor = valor / 10;
                    
                    patternInput[0][i] = valor;
                }
                neuronioEsperado = Integer.parseInt(split[split.length - 1].trim());
                
                for (int i = 0; i < 10; i++) {
                    //a ultima posicao do arquivo e destinado a classe esperada
                    if ((i + 1) == neuronioEsperado){
                        expectedOutput[0][i] = 1.0;
                    }
                    else
                        expectedOutput[0][i] = 0.0;
                }
                
                rede.setTrainingData(patternInput, expectedOutput);
                rede.train(100);
                
                atualizaListaResultados(neuronioEsperado);
                
                linha = lerArq.readLine(); // lê da segunda até a última linha
                qtdeLinhasLidas++;
            }

            jMessage.setText("");
            
            arq.close();
        } catch (IOException e) {
            System.err.printf("Erro na abertura do arquivo: %s.\n",
            e.getMessage());
        }
        
        
        long tempoFinal = System.currentTimeMillis();
        
        System.out.println("o metodo executou em " + (tempoFinal - tempoInicial));
    }
    
    private void atualizaListaResultados(int resultadoEsperado){
        Double[] saida = rede.getOutput();
        int indice = 0;
        Double maiorValor = 0.0;
        Neuronio neuronioTemp  = new Neuronio();
        
        for (int i = 0; i < saida.length; i++) {//seta cor
            if (saida[i] > maiorValor){
                indice = i;
                maiorValor = saida[i];
            }
        }
        neuronioTemp.setId(resultadoEsperado);
        neuronioTemp.setResultadoObtido(indice);
                
        lstResultados.add(neuronioTemp);
    }
    
    private void loadAmostraTemporaria(){
        Double maiorValor = 0.0;
        int indice = 0;
        Double[][] patternInputUniq   = new Double[1][16];
        Double[][] expectedOutputUniq = new Double[1][10]; 
        Neuronio neuronioTemp         = new Neuronio();
        
        patternInputUniq[0][0] = 4.7 ;
        patternInputUniq[0][1] = 10.0;
        patternInputUniq[0][2] = 2.7;
        patternInputUniq[0][3] = 8.1;
        patternInputUniq[0][4] = 5.7;
        patternInputUniq[0][5] = 3.7;
        patternInputUniq[0][6] = 2.6;
        patternInputUniq[0][7] = 0.0;
        patternInputUniq[0][8] = 0.0;
        patternInputUniq[0][9] = 2.3;
        patternInputUniq[0][10] = 5.6;
        patternInputUniq[0][11] = 5.3;
        patternInputUniq[0][12] = 10.0;
        patternInputUniq[0][13] = 9.0;
        patternInputUniq[0][14] = 4.0;
        patternInputUniq[0][15] = 9.8;
                
        expectedOutputUniq[0][0]  = 0.0;
        expectedOutputUniq[0][1]  = 0.0;
        expectedOutputUniq[0][2]  = 0.0;
        expectedOutputUniq[0][3]  = 0.0;
        expectedOutputUniq[0][4]  = 0.0;
        expectedOutputUniq[0][5]  = 0.0;
        expectedOutputUniq[0][6]  = 0.0;
        expectedOutputUniq[0][7]  = 1.0;
        expectedOutputUniq[0][8]  = 0.0;
        expectedOutputUniq[0][9]  = 0.0;
        
        rede.setTrainingData(patternInputUniq, expectedOutputUniq);
        double erro = rede.train(100); //treinamento
        
        Double[] saida = rede.getOutput();
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTabela.getModel();
        tabelaModelo.setNumRows(0); //limpa a tabela
        for (int i = 0; i < saida.length; i++) {//seta cor
            tabelaModelo.addRow(new String[]{"Neuronio " + (i + 1), "" + formater.format(saida[i])}); 
            
            if (saida[i] > maiorValor){
                indice = i;
                maiorValor = saida[i];
            }
        }
        jTabela.setRowSelectionInterval(indice, indice);
        
        
        neuronioTemp.setId(8);
        neuronioTemp.setResultadoObtido(indice);
                
        lstResultados.add(neuronioTemp);
    }
    
    private void initRede(){
        rede = new Backpropagation();
    }
    
    private void initMatrizConfusao(){
        jMatrizConfusao.setEnabled(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jMatrizConfusao;
    private javax.swing.JLabel jMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField jTestValores;
    // End of variables declaration//GEN-END:variables
}
